language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.10.1
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
script: 
  - flake8 --ignore=E501,F401 --max-line-length=99
  - python manage.py test
  - coverage run --source='.' manage.py test
after_success:
  - coverage report
