# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-24 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ordered',
            field=models.PositiveIntegerField(default=0, verbose_name='\u0417\u0430\u043a\u0430\u0437\u0430\u043d\u043e'),
            preserve_default=False,
        ),
    ]
